name: DB Ping

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once a day at midnight
  workflow_dispatch:

jobs:
  ping-db:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client

      - name: Run DB check
        run: |
          psql "$SUPABASE_DATABASE_URL" -c "SELECT 1;"
        env:
          SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}